# Generated by Django 5.1.6 on 2025-02-25 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название эксперимента')),
                ('status', models.CharField(choices=[('create', 'Создан'), ('update', 'Обновлен'), ('delete', 'Удалён'), ('started', 'Запущен'), ('finished', 'Завершен'), ('stopped', 'Остановлен'), ('error', 'Ошибка')], default='create', max_length=255, verbose_name='Статус эксперимента')),
                ('results_folder', models.CharField(blank=True, max_length=255, verbose_name='Папка результатов')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания эксперимента', verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления данных эксперимента', verbose_name='Время обновления')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, запустивший эксперимент', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Эксперимент',
                'verbose_name_plural': 'Эксперименты',
            },
        ),
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название конфигурации')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания конфигурации', verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления данных конфигурации', verbose_name='Время обновления')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, создавший конфигурацию', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'User Config',
                'verbose_name_plural': 'User Configs',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена'), ('stopped', 'Остановлена'), ('error', 'Ошибка')], max_length=255, verbose_name='Статус задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания задачи', verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления данных задачи', verbose_name='Время обновления')),
                ('experiment', models.ForeignKey(help_text='В рамках какого эксперимента создана задача', on_delete=django.db.models.deletion.CASCADE, to='task_modeling.experiment', verbose_name='Связь с экспериментом')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_modeling.taskconfig', verbose_name='Конфигурация задачи')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
