# Generated by Django 5.1.6 on 2025-02-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskconfig',
            options={'verbose_name': 'Конфигурация задачи', 'verbose_name_plural': 'Конфигурации задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена'), ('stopped', 'Остановлена'), ('error', 'Ошибка')], default='created', max_length=255, verbose_name='Статус задачи'),
        ),
    ]
