# Generated by Django 5.1.6 on 2025-02-25 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_modeling', '0002_alter_task_created_at_alter_task_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_folder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Task folder'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Task model'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Config name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('started', 'Started'), ('finished', 'Finished'), ('stopped', 'Stopped'), ('error', 'Error')], default='create', max_length=255, verbose_name='Status'),
        ),
    ]
