# Generated by Django 5.1.6 on 2025-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_modeling", "0003_remove_experiment_results_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="ID Celery задачи",
                null=True,
                verbose_name="ID celery задачи",
            ),
        ),
    ]
