volumes:
  pg_data: { }

services:
  postgres:
    container_name: postgres_alert_system
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql/dumps:/modeling_system/dumps
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A modeling_system_backend worker --loglevel=info --logfile=media/logs/celery.log --concurrency=8
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - C_FORCE_ROOT=true

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

#  web:
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile
#    env_file:
#      - .env
#    environment:
#      POSTGRES_HOST: postgres
#    volumes:
#      - .:/modeling_system
#    ports:
#      - '8000:8000'
#    depends_on:
#      - postgres