volumes:
  pg_data: { }
  flower_data:

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql/dumps:/modeling_system/dumps
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A modeling_system_backend worker --loglevel=debug --logfile=media/logs/celery.log --concurrency=8 --hostname=worker@%h
    volumes:
      - .:/code
    user: "33:33"
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - C_FORCE_ROOT=true

  flower:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A modeling_system_backend flower --conf=flowerconfig.py
    ports:
      - "5555:5555"
    volumes:
      - ./flower/flowerconfig.py:/code/flowerconfig.py
      - flower_data:/data
    depends_on:
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

#  backend:
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile
#    env_file:
#      - .env
#    environment:
#      POSTGRES_HOST: postgres
#      REDIS_HOST: redis
#    volumes:
#      - .:/modeling_system
#    ports:
#      - '8000:8000'
#    depends_on:
#      - postgres
#      - redis
#
#  frontend:
#    build: ../frontend/.
#    ports:
#      - "5173:5173"
#    volumes:
#      - ../frontend:/app
#      - /app/node_modules
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#      - VITE_API_URL=${VITE_API_URL}
