# Generated by Django 5.1.6 on 2025-04-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
