name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: 📥 Checkout репозиторий
      uses: actions/checkout@v4

    - name: 🐍 Установка Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: 📦 Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🔧 Применение миграций
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      run: |
        python manage.py migrate

    - name: ✅ Запуск тестов с `pytest`
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      run: |
        pytest --cov=. --cov-report=xml

    - name: 📏 Проверка кода `black`
      run: |
        black --check .

    - name: ☁️ Загрузка отчёта покрытия
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
